[project]
name = "hnsw-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["pytest>=8.3.5"]

[tool.uv]
package = true
[project.scripts]
evaluate = "hnsw.main:main"
[dependency-groups]
dev = ["pytest>=8.3.5"]
